// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_models.sql

package db

import (
	"context"
	"database/sql"
)

const deleteSessionModels = `-- name: DeleteSessionModels :exec
DELETE FROM session_models
WHERE session_id = ?
`

func (q *Queries) DeleteSessionModels(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionModelsStmt, deleteSessionModels, sessionID)
	return err
}

const listSessionModels = `-- name: ListSessionModels :many
SELECT session_id, model_type, provider, model, selected_model_json, updated_at, created_at
FROM session_models
WHERE session_id = ?
ORDER BY model_type
`

func (q *Queries) ListSessionModels(ctx context.Context, sessionID string) ([]SessionModel, error) {
	rows, err := q.query(ctx, q.listSessionModelsStmt, listSessionModels, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionModel{}
	for rows.Next() {
		var i SessionModel
		if err := rows.Scan(
			&i.SessionID,
			&i.ModelType,
			&i.Provider,
			&i.Model,
			&i.SelectedModelJson,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSessionModel = `-- name: UpsertSessionModel :one
INSERT INTO session_models (
    session_id,
    model_type,
    provider,
    model,
    selected_model_json,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
)
ON CONFLICT(session_id, model_type) DO UPDATE SET
    provider = excluded.provider,
    model = excluded.model,
    selected_model_json = excluded.selected_model_json,
    updated_at = strftime('%s', 'now')
RETURNING session_id, model_type, provider, model, selected_model_json, updated_at, created_at
`

type UpsertSessionModelParams struct {
	SessionID         string         `json:"session_id"`
	ModelType         string         `json:"model_type"`
	Provider          string         `json:"provider"`
	Model             string         `json:"model"`
	SelectedModelJson sql.NullString `json:"selected_model_json"`
}

func (q *Queries) UpsertSessionModel(ctx context.Context, arg UpsertSessionModelParams) (SessionModel, error) {
	row := q.queryRow(ctx, q.upsertSessionModelStmt, upsertSessionModel,
		arg.SessionID,
		arg.ModelType,
		arg.Provider,
		arg.Model,
		arg.SelectedModelJson,
	)
	var i SessionModel
	err := row.Scan(
		&i.SessionID,
		&i.ModelType,
		&i.Provider,
		&i.Model,
		&i.SelectedModelJson,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
